### ISSUE TITLE
Where is Paper, please?

### ISSUE THREAD

**Issue by ruidongtd** [S1s-Z/QUEEN#1]
Where is Paper, please?

**Comment by S1s-Z** [comment]
you can find our work here :) https://aclanthology.org/2022.naacl-main.356.pdf

**Comment by ruidongtd** [comment]
> you can find our work here :) https://aclanthology.org/2022.naacl-main.356.pdf

thanks!

**Comment by ruidongtd** [comment]
> you can find our work here :) https://aclanthology.org/2022.naacl-main.356.pdf

Will the code be open source?

**Comment by S1s-Z** [comment]
> 

we sent a email for your request

**Comment by S1s-Z** [comment]
> > you can find our work here :) https://aclanthology.org/2022.naacl-main.356.pdf
> 
> Will the code be open source?

we sent a email for your request

**Comment by MinJeongwon** [comment]
Hi, thank you for sharing your great work.
Can I also get the codes and data for this project?
Thanks!
